- name: Demo on Conditions
  hosts: local
  connection: local
  vars:
    is_live: true
  tasks:
  - name: print message if is_live is true
    ansible.builtin.debug:
      msg: "Welcome to Ansible Training"
    when: is_live