- name: demo on loops
  hosts: local
  connection: local
  tasks: 
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}" #item is reserved word in ansible for loops
    loop:
      - Ansible
      - DevOps
      - Linux